name: ima
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi>=0.135,<0.136
      - playwright>=1.58,<1.59
      - pydantic>=2.12,<3
      - python-dotenv>=1.0,<2
      - pywinauto>=0.6.9,<0.7
      - tenacity>=9.1,<10
      - uvicorn>=0.41,<0.42
      - pytest>=9,<10
